export const surveys = [
  {
    id: 1,
    title: "Student Mental Health Screening",
    description: "Initial mental health screening for new students",
    surveyType: "screening",
    isRequired: true,
    isRecurring: false,
    recurringCycle: "NONE",
    startDate: "2025-07-20",
    endDate: "2025-12-30",
    category: {
      id: 1,
      name: "Anxiety Assessment",
      code: "ANX",
      description: "Assessment for anxiety levels and symptoms",
      isLimitted: true,
      questionLength: 10,
      isSum: true,
      isActive: true,
      severityWeight: 1.5,
    }, // Mental Health Assessment Category
    targetGroup: "GRADE",
    targetGrade: "10",
    status: "PUBLISHED",
    createdAt: "2024-03-01T08:00:00",
    updatedAt: "2024-03-01T08:00:00",
    createdBy: 1,
    questions: [
      {
        id: 1,
        surveyId: 1,
        text: "How often do you feel anxious at school?",
        description:
          "Please select the option that best describes your experience",
        isActive: true,
        createdAt: "2024-03-01",
        updatedAt: "2024-03-01",
        questionType: "LIKERT_SCALE",
        isRequired: true,
        answers: [
          {
            id: 1,
            questionId: 1,
            text: "Never",
            score: 1,
          },
          {
            id: 2,
            questionId: 1,
            text: "Rarely",
            score: 2,
          },
          {
            id: 3,
            questionId: 1,
            text: "Sometimes",
            score: 3,
          },
          {
            id: 4,
            questionId: 1,
            text: "Often",
            score: 4,
          },
          {
            id: 5,
            questionId: 1,
            text: "Always",
            score: 5,
          },
        ],
      },
      {
        id: 2,
        surveyId: 1,
        text: "Which of these support services would you be interested in?",
        description: "Select all that apply to your needs",
        isActive: true,
        createdAt: "2024-03-01",
        updatedAt: "2024-03-01",
        questionType: "LIKERT_SCALE",
        isRequired: true,
        answers: [
          {
            id: 6,
            questionId: 2,
            text: "Individual Counseling",
            score: 0,
          },
          {
            id: 7,
            questionId: 2,
            text: "Group Therapy",
            score: 0,
          },
          {
            id: 8,
            questionId: 2,
            text: "Academic Support",
            score: 0,
          },
          {
            id: 9,
            questionId: 2,
            text: "Peer Support Groups",
            score: 0,
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: "Monthly Well-being Check",
    description: "Regular check-in for student well-being",
    surveyType: "followup",
    isRequired: true,
    isRecurring: true,
    recurringCycle: "MONTHLY",
    startDate: "2025-07-20",
    endDate: "2025-12-30",
    category: {
      id: 1,
      name: "Anxiety Assessment",
      code: "ANX",
      description: "Assessment for anxiety levels and symptoms",
      isLimitted: true,
      questionLength: 10,
      isSum: true,
      isActive: true,
      severityWeight: 1.5,
    }, // Well-being Assessment Category
    targetGroup: "ALL",
    targetGrade: "NONE",
    status: "PUBLISHED",
    createdAt: "2024-03-01T09:00:00",
    updatedAt: "2024-03-01T09:00:00",
    createdBy: 1,
    questions: [
      {
        id: 3,
        surveyId: 2,
        text: "Rate your overall stress level this month",
        description: "Consider your academic and personal life",
        isActive: true,
        createdAt: "2024-03-01",
        updatedAt: "2024-03-01",
        questionType: "LIKERT_SCALE",
        isRequired: true,
        answers: [
          {
            id: 10,
            questionId: 3,
            text: "Very Low",
            score: 1,
          },
          {
            id: 11,
            questionId: 3,
            text: "Low",
            score: 2,
          },
          {
            id: 12,
            questionId: 3,
            text: "Moderate",
            score: 3,
          },
          {
            id: 13,
            questionId: 3,
            text: "High",
            score: 4,
          },
          {
            id: 14,
            questionId: 3,
            text: "Very High",
            score: 5,
          },
        ],
      },
    ],
  },
  {
    id: 3,
    title: "Exit Survey - Grade 12",
    description: "Final assessment for graduating students",
    surveyType: "exit",
    isRequired: true,
    isRecurring: false,
    recurringCycle: "NONE",
    startDate: "2025-07-20",
    endDate: "2025-12-30",
    category: {
      id: 1,
      name: "Anxiety Assessment",
      code: "ANX",
      description: "Assessment for anxiety levels and symptoms",
      isLimitted: true,
      questionLength: 10,
      isSum: true,
      isActive: true,
      severityWeight: 1.5,
    }, // Exit Assessment Category
    targetGroup: "GRADE",
    targetGrade: "12",
    status: "DRAFT",
    createdAt: "2024-03-01T10:00:00",
    updatedAt: "2024-03-01T10:00:00",
    createdBy: 1,
    questions: [
      {
        id: 4,
        surveyId: 3,
        text: "How satisfied are you with the school's psychological support services?",
        description: "Please rate your overall experience",
        isActive: true,
        createdAt: "2024-03-01",
        updatedAt: "2024-03-01",
        questionType: "LIKERT_SCALE",
        isRequired: true,
        answers: [
          {
            id: 15,
            questionId: 4,
            text: "Very Dissatisfied",
            score: 1,
          },
          {
            id: 16,
            questionId: 4,
            text: "Dissatisfied",
            score: 2,
          },
          {
            id: 17,
            questionId: 4,
            text: "Neutral",
            score: 3,
          },
          {
            id: 18,
            questionId: 4,
            text: "Satisfied",
            score: 4,
          },
          {
            id: 19,
            questionId: 4,
            text: "Very Satisfied",
            score: 5,
          },
        ],
      },
    ],
  },
];

export const categories = [
  {
    id: 1,
    name: "Anxiety Assessment",
    code: "ANX",
    description: "Assessment for anxiety levels and symptoms",
    isLimitted: true,
    questionLength: 10,
    isSum: true,
    isActive: true,
    severityWeight: 1.5,
  },
  {
    id: 2,
    name: "Depression Screening",
    code: "DEP",
    description: "Screening for depression symptoms",
    isLimitted: true,
    questionLength: 15,
    isSum: true,
    isActive: true,
    severityWeight: 2.0,
  },
  {
    id: 3,
    name: "Academic Stress",
    code: "ACS",
    description: "Assessment of academic-related stress",
    isLimitted: false,
    questionLength: 8,
    isSum: true,
    isActive: true,
    severityWeight: 1.0,
  },
];

export const levels = [
  {
    id: 1,
    label: "Minimal Anxiety",
    code: "ANX-LOW",
    minScore: 0,
    maxScore: 4,
    levelType: "low",
    description: "Minimal or no anxiety symptoms",
    category: {
      id: 1,
      name: "Anxiety Assessment",
      code: "ANX",
      description: "Assessment for anxiety levels and symptoms",
      isLimitted: true,
      questionLength: 10,
      isSum: true,
      isActive: true,
      severityWeight: 1.5,
    },
    symptomsDescription: "Few or no symptoms of anxiety present",
    interventionRequired:
      "No immediate intervention required. Continue routine monitoring.",
  },
  {
    id: 2,
    label: "Mild Anxiety",
    code: "ANX-MILD",
    minScore: 5,
    maxScore: 9,
    levelType: "mild",
    description: "Mild anxiety symptoms present",
    category: {
      id: 1,
      name: "Anxiety Assessment",
      code: "ANX",
      description: "Assessment for anxiety levels and symptoms",
      isLimitted: true,
      questionLength: 10,
      isSum: true,
      isActive: true,
      severityWeight: 1.5,
    },
    symptomsDescription: "Occasional worry, mild nervousness",
    interventionRequired: "Consider self-help resources and monitoring",
  },
  {
    id: 3,
    label: "Moderate Depression",
    code: "DEP-MOD",
    minScore: 10,
    maxScore: 14,
    levelType: "moderate",
    description: "Moderate depression symptoms",
    category: {
      id: 2,
      name: "Depression Screening",
      code: "DEP",
      description: "Screening for depression symptoms",
      isLimitted: true,
      questionLength: 15,
      isSum: true,
      isActive: true,
      severityWeight: 2.0,
    },
    symptomsDescription: "Persistent low mood, reduced interest in activities",
    interventionRequired: "Regular counseling sessions recommended",
  },
  {
    id: 4,
    label: "High Academic Stress",
    code: "ACS-SEV",
    minScore: 15,
    maxScore: 20,
    levelType: "severe",
    description: "Severe academic stress levels",
    category: {
      id: 3,
      name: "Academic Stress",
      code: "ACS",
      description: "Assessment of academic-related stress",
      isLimitted: false,
      questionLength: 8,
      isSum: true,
      isActive: true,
      severityWeight: 1.0,
    },
    symptomsDescription: "Significant difficulty managing academic workload",
    interventionRequired:
      "Immediate academic counseling and stress management intervention",
  },
];

export const surveyRecords = [
  {
    id: 1,
    surveyId: 1,
    studentId: 1,
    caseId: null,
    level: {
      id: 2,
      label: "Mild Anxiety",
      code: "ANX-MILD",
      minScore: 5,
      maxScore: 9,
      levelType: "mild",
      description: "Mild anxiety symptoms present",
      category: {
        id: 1,
        name: "Anxiety Assessment",
        code: "ANX",
        description: "Assessment for anxiety levels and symptoms",
        isLimitted: true,
        questionLength: 10,
        isSum: true,
        isActive: true,
        severityWeight: 1.5,
      },
      symptomsDescription: "Occasional worry, mild nervousness",
      interventionRequired: "Consider self-help resources and monitoring",
    }, // Mild Anxiety
    totalScore: 7.5,
    isSkipped: false,
    completedAt: "2025-07-20",
    createdAt: "2025-07-20",
    updatedAt: "2025-07-20",
    answers: [
      {
        questionId: 1,
        selectedAnswerId: 3,
        score: 3,
      },
      {
        questionId: 2,
        selectedAnswerId: 6,
        score: 0,
      },
    ],
  },
  {
    id: 2,
    surveyId: 2,
    studentId: 1,
    caseId: 1,
    level: {
      id: 3,
      label: "Moderate Depression",
      code: "DEP-MOD",
      minScore: 10,
      maxScore: 14,
      levelType: "moderate",
      description: "Moderate depression symptoms",
      category: {
        id: 2,
        name: "Depression Screening",
        code: "DEP",
        description: "Screening for depression symptoms",
        isLimitted: true,
        questionLength: 15,
        isSum: true,
        isActive: true,
        severityWeight: 2.0,
      },
      symptomsDescription:
        "Persistent low mood, reduced interest in activities",
      interventionRequired: "Regular counseling sessions recommended",
    }, // Moderate Depression
    totalScore: 12.0,
    isSkipped: false,
    completedAt: "2025-08-20",
    createdAt: "2025-08-20",
    updatedAt: "2025-08-20",
    answers: [
      {
        questionId: 3,
        selectedAnswerId: 13,
        score: 4,
      },
    ],
  },
  {
    id: 3,
    surveyId: 3,
    studentId: 2,
    caseId: 2,
    level: {
      id: 4,
      label: "High Academic Stress",
      code: "ACS-SEV",
      minScore: 15,
      maxScore: 20,
      levelType: "severe",
      description: "Severe academic stress levels",
      category: {
        id: 3,
        name: "Academic Stress",
        code: "ACS",
        description: "Assessment of academic-related stress",
        isLimitted: false,
        questionLength: 8,
        isSum: true,
        isActive: true,
        severityWeight: 1.0,
      },
      symptomsDescription: "Significant difficulty managing academic workload",
      interventionRequired:
        "Immediate academic counseling and stress management intervention",
    }, // High Academic Stress
    totalScore: 16.5,
    isSkipped: false,
    completedAt: "2025-09-15",
    createdAt: "2025-09-15",
    updatedAt: "2025-09-15",
    answers: [
      {
        questionId: 4,
        selectedAnswerId: 18,
        score: 4,
      },
    ],
  },
  {
    id: 4,
    surveyId: 1,
    studentId: 3,
    caseId: null,
    level: {
      id: 1,
      label: "Minimal Anxiety",
      code: "ANX-LOW",
      minScore: 0,
      maxScore: 4,
      levelType: "low",
      description: "Minimal or no anxiety symptoms",
      category: {
        id: 1,
        name: "Anxiety Assessment",
        code: "ANX",
        description: "Assessment for anxiety levels and symptoms",
        isLimitted: true,
        questionLength: 10,
        isSum: true,
        isActive: true,
        severityWeight: 1.5,
      },
      symptomsDescription: "Few or no symptoms of anxiety present",
      interventionRequired:
        "No immediate intervention required. Continue routine monitoring.",
    }, // Minimal Anxiety
    totalScore: 3.5,
    isSkipped: false,
    completedAt: "2025-07-21",
    createdAt: "2025-07-21",
    updatedAt: "2025-07-21",
    answers: [
      {
        questionId: 1,
        selectedAnswerId: 2,
        score: 2,
      },
      {
        questionId: 2,
        selectedAnswerId: 6, // Single selection in multiple choice
        score: 0,
      },
    ],
  },
];

export const responseData = [
  {
    category: {
      code: "EMO",
      description: "Emotional Health",
      id: 1,
      isActive: true,
      isLimited: false,
      isSum: true,
      maxScore: 5,
      minScore: 0,
      name: "Emotional",
      questionLength: 10,
      severityWeight: 1.5,
    },
    createdAt: "2025-07-25T17:34:01.200177",
    createdBy: null,
    description: "1",
    endDate: "2025-07-30",
    isRecurring: false,
    isRequired: true,
    recurringCycle: "NONE",
    startDate: "2025-07-26",
    status: "PUBLISHED",
    surveyId: 3,
    surveyType: "SCREENING",
    targetGrade: [[Object], [Object], [Object]],
    targetScope: "ALL",
    title: "Test",
    updatedAt: "2025-07-25T17:34:01.200201",
  },
  {
    category: {
      code: "EMO",
      description: "Emotional Health",
      id: 1,
      isActive: true,
      isLimited: false,
      isSum: true,
      maxScore: 5,
      minScore: 0,
      name: "Emotional",
      questionLength: 10,
      severityWeight: 1.5,
    },
    createdAt: "2025-07-25T17:46:49.744138",
    createdBy: null,
    description: "1",
    endDate: "2025-07-30",
    isRecurring: false,
    isRequired: true,
    recurringCycle: "NONE",
    startDate: "2025-07-26",
    status: "PUBLISHED",
    surveyId: 4,
    surveyType: "SCREENING",
    targetGrade: [[Object], [Object]],
    targetScope: "GRADE",
    title: "Test 2 ",
    updatedAt: "2025-07-25T17:46:49.744149",
  },
  {
    category: {
      code: "EMO",
      description: "Emotional Health",
      id: 1,
      isActive: true,
      isLimited: false,
      isSum: true,
      maxScore: 5,
      minScore: 0,
      name: "Emotional",
      questionLength: 10,
      severityWeight: 1.5,
    },
    createdAt: "2025-07-25T18:37:30.251095",
    createdBy: null,
    description: "1",
    endDate: "2025-07-30",
    isRecurring: false,
    isRequired: false,
    recurringCycle: "NONE",
    startDate: "2025-07-26",
    status: "PUBLISHED",
    surveyId: 5,
    surveyType: "SCREENING",
    targetGrade: [[Object], [Object], [Object]],
    targetScope: "ALL",
    title: "Test",
    updatedAt: "2025-07-25T18:37:30.251105",
  },
];
