export const reportData = [
  {
    id: 'anxiety_persistent',
    label: 'Lo âu kéo dài',
    categoryCode: 'mental_health',
    description: 'Dựa trên thang đo GAD‑7, RCADS‑25',
    evidenceLevel: 'Strong',
    reference: 'Spence, S.H. (1998). RCADS Manual. Griffith University.',
    questions: [
      {
        type: 'frequency',
        label: 'Tần suất xuất hiện',
        options: [
          { score: 0, text: 'Không bao giờ hoặc hiếm khi' },
          { score: 1, text: 'Ít hơn 1‑2 ngày trong tuần' },
          { score: 2, text: 'Một vài ngày trong tuần (2‑3 ngày)' },
          { score: 3, text: 'Hơn nửa số ngày trong tuần (4‑5 ngày)' },
          { score: 4, text: 'Hầu như mỗi ngày (6‑7 ngày)' },
          { score: 5, text: 'Liên tục, nguy cơ cao' },
        ],
      },
      {
        type: 'impairment',
        label: 'Mức độ ảnh hưởng',
        options: [
          { score: 0, text: 'Không ảnh hưởng đến chức năng' },
          { score: 1, text: 'Ảnh hưởng tối thiểu, hầu như không nhận thấy' },
          { score: 2, text: 'Ảnh hưởng nhẹ đến học tập hoặc quan hệ xã hội' },
          { score: 3, text: 'Ảnh hưởng trung bình đến nhiều lĩnh vực' },
          { score: 4, text: 'Ảnh hưởng nghiêm trọng đến hầu hết lĩnh vực' },
          { score: 5, text: 'Không thể thực hiện chức năng cơ bản' },
        ],
      },
      {
        type: 'duration',
        label: 'Thời gian kéo dài',
        options: [
          { score: 0, text: 'Không có' },
          { score: 1, text: 'Dưới 1 tuần' },
          { score: 2, text: '1‑2 tuần' },
          { score: 3, text: '2‑4 tuần' },
          { score: 4, text: '1‑3 tháng' },
          { score: 5, text: 'Hơn 3 tháng hoặc mạn tính' },
        ],
      },
    ],
  },
  {
    id: 'sleep_disorder',
    label: 'Rối loạn giấc ngủ',
    categoryCode: 'mental_health',
    description:
      'Theo Sleep Medicine Reviews, ảnh hưởng đến chất lượng học tập',
    evidenceLevel: 'Moderate',
    reference: 'Owens, J.A. (2014). Sleep Medicine Reviews, 18(4), 313‑319.',
    questions: [
      {
        type: 'frequency',
        label: 'Tần suất rối loạn giấc ngủ',
        options: [
          { score: 0, text: 'Không bao giờ hoặc hiếm khi' },
          { score: 1, text: 'Ít hơn 1‑2 ngày trong tuần' },
          { score: 2, text: 'Một vài ngày trong tuần (2‑3 ngày)' },
          { score: 3, text: 'Hơn nửa số ngày trong tuần (4‑5 ngày)' },
          { score: 4, text: 'Hầu như mỗi ngày (6‑7 ngày)' },
          { score: 5, text: 'Liên tục, nguy cơ cao' },
        ],
      },
      {
        type: 'impairment',
        label: 'Ảnh hưởng đến học tập/xã hội',
        options: [
          { score: 0, text: 'Không ảnh hưởng đến chức năng' },
          { score: 1, text: 'Ảnh hưởng tối thiểu, hầu như không nhận thấy' },
          { score: 2, text: 'Ảnh hưởng nhẹ đến học tập hoặc quan hệ xã hội' },
          { score: 3, text: 'Ảnh hưởng trung bình đến nhiều lĩnh vực' },
          { score: 4, text: 'Ảnh hưởng nghiêm trọng đến hầu hết lĩnh vực' },
          { score: 5, text: 'Không thể thực hiện chức năng cơ bản' },
        ],
      },
      {
        type: 'duration',
        label: 'Thời gian kéo dài',
        options: [
          { score: 0, text: 'Không có' },
          { score: 1, text: 'Dưới 1 tuần' },
          { score: 2, text: '1‑2 tuần' },
          { score: 3, text: '2‑4 tuần' },
          { score: 4, text: '1‑3 tháng' },
          { score: 5, text: 'Hơn 3 tháng hoặc mạn tính' },
        ],
      },
    ],
  },
  {
    id: 'depression_symptoms',
    label: 'Triệu chứng trầm cảm',
    categoryCode: 'mental_health',
    description: 'Theo PHQ‑A, biểu hiện của rối loạn khí sắc',
    evidenceLevel: 'Strong',
    reference:
      'Johnson, J.G. et al. (2002). J Adolescent Health, 30(3), 196‑204.',
    questions: [
      {
        type: 'frequency',
        label: 'Tần suất triệu chứng trầm cảm',
        options: [
          { score: 0, text: 'Không bao giờ hoặc hiếm khi' },
          { score: 1, text: 'Ít hơn 1‑2 ngày trong tuần' },
          { score: 2, text: 'Một vài ngày trong tuần (2‑3 ngày)' },
          { score: 3, text: 'Hơn nửa số ngày trong tuần (4‑5 ngày)' },
          { score: 4, text: 'Hầu như mỗi ngày (6‑7 ngày)' },
          { score: 5, text: 'Liên tục, nguy cơ cao' },
        ],
      },
      {
        type: 'impairment',
        label: 'Ảnh hưởng đến hoạt động và xã hội',
        options: [
          { score: 0, text: 'Không ảnh hưởng đến chức năng' },
          { score: 1, text: 'Ảnh hưởng tối thiểu, hầu như không nhận thấy' },
          { score: 2, text: 'Ảnh hưởng nhẹ đến học tập hoặc quan hệ xã hội' },
          { score: 3, text: 'Ảnh hưởng trung bình đến nhiều lĩnh vực' },
          { score: 4, text: 'Ảnh hưởng nghiêm trọng đến hầu hết lĩnh vực' },
          { score: 5, text: 'Không thể thực hiện chức năng cơ bản' },
        ],
      },
      {
        type: 'duration',
        label: 'Thời gian kéo dài',
        options: [
          { score: 0, text: 'Không có' },
          { score: 1, text: 'Dưới 1 tuần' },
          { score: 2, text: '1‑2 tuần' },
          { score: 3, text: '2‑4 tuần' },
          { score: 4, text: '1‑3 tháng' },
          { score: 5, text: 'Hơn 3 tháng hoặc mạn tính' },
        ],
      },
    ],
  },
  {
    id: 'low_self_esteem',
    label: 'Lòng tự trọng thấp',
    categoryCode: 'mental_health',
    description: 'Dựa trên thang đo Rosenberg',
    evidenceLevel: 'Moderate',
    reference: 'Rosenberg, M. (1965). Rosenberg Self‑Esteem Scale.',
    questions: [
      {
        type: 'frequency',
        label: 'Tần suất cảm giác lòng tự trọng thấp',
        options: [
          { score: 0, text: 'Không bao giờ hoặc hiếm khi' },
          { score: 1, text: 'Ít hơn 1‑2 ngày trong tuần' },
          { score: 2, text: 'Một vài ngày trong tuần (2‑3 ngày)' },
          { score: 3, text: 'Hơn nửa số ngày trong tuần (4‑5 ngày)' },
          { score: 4, text: 'Hầu như mỗi ngày (6‑7 ngày)' },
          { score: 5, text: 'Liên tục, nguy cơ cao' },
        ],
      },
      {
        type: 'impairment',
        label: 'Ảnh hưởng đến mối quan hệ/xã hội',
        options: [
          { score: 0, text: 'Không ảnh hưởng đến chức năng' },
          { score: 1, text: 'Ảnh hưởng tối thiểu, hầu như không nhận thấy' },
          { score: 2, text: 'Ảnh hưởng nhẹ đến học tập hoặc quan hệ xã hội' },
          { score: 3, text: 'Ảnh hưởng trung bình đến nhiều lĩnh vực' },
          { score: 4, text: 'Ảnh hưởng nghiêm trọng đến hầu hết lĩnh vực' },
          { score: 5, text: 'Không thể thực hiện chức năng cơ bản' },
        ],
      },
      {
        type: 'duration',
        label: 'Thời gian kéo dài',
        options: [
          { score: 0, text: 'Không có' },
          { score: 1, text: 'Dưới 1 tuần' },
          { score: 2, text: '1‑2 tuần' },
          { score: 3, text: '2‑4 tuần' },
          { score: 4, text: '1‑3 tháng' },
          { score: 5, text: 'Hơn 3 tháng hoặc mạn tính' },
        ],
      },
    ],
  },
  {
    id: 'self_harm_ideation',
    label: 'Ý nghĩ tự hại/tự tử',
    categoryCode: 'mental_health',
    description: 'Rủi ro cao, cần đánh giá an toàn ngay lập tức',
    evidenceLevel: 'Strong',
    reference: 'Posner, K. et al. (2011). Am J Psychiatry, 168(12), 1266‑1277.',
    questions: [
      {
        type: 'frequency',
        label: 'Tần suất ý nghĩ tự hại/tự tử',
        options: [
          { score: 0, text: 'Không bao giờ hoặc hiếm khi' },
          { score: 1, text: 'Ít hơn 1‑2 ngày trong tuần' },
          { score: 2, text: 'Một vài ngày trong tuần (2‑3 ngày)' },
          { score: 3, text: 'Hơn nửa số ngày trong tuần (4‑5 ngày)' },
          { score: 4, text: 'Hầu như mỗi ngày (6‑7 ngày)' },
          { score: 5, text: 'Liên tục, nguy cơ cao' },
        ],
      },
      {
        type: 'impairment',
        label: 'Ảnh hưởng đến chức năng/sinh hoạt',
        options: [
          { score: 0, text: 'Không ảnh hưởng đến chức năng' },
          { score: 1, text: 'Ảnh hưởng tối thiểu, hầu như không nhận thấy' },
          { score: 2, text: 'Ảnh hưởng nhẹ đến học tập hoặc quan hệ xã hội' },
          { score: 3, text: 'Ảnh hưởng trung bình đến nhiều lĩnh vực' },
          { score: 4, text: 'Ảnh hưởng nghiêm trọng đến hầu hết lĩnh vực' },
          { score: 5, text: 'Không thể thực hiện chức năng cơ bản' },
        ],
      },
      {
        type: 'duration',
        label: 'Thời gian kéo dài',
        options: [
          { score: 0, text: 'Không có' },
          { score: 1, text: 'Dưới 1 tuần' },
          { score: 2, text: '1‑2 tuần' },
          { score: 3, text: '2‑4 tuần' },
          { score: 4, text: '1‑3 tháng' },
          { score: 5, text: 'Hơn 3 tháng hoặc mạn tính' },
        ],
      },
    ],
  },
  {
    id: 'family_conflict',
    label: 'Xung đột gia đình',
    categoryCode: 'environment',
    description: 'Ảnh hưởng lâu dài đến phát triển tâm lý trẻ',
    evidenceLevel: 'Strong',
    reference:
      'Cummings, E.M. & Davies, P.T. (2010). Annual Review of Psychology, 61, 237‑263.',
    questions: [
      {
        type: 'frequency',
        label: 'Tần suất xung đột gia đình',
        options: [
          { score: 0, text: 'Không bao giờ hoặc hiếm khi' },
          { score: 1, text: 'Ít hơn 1‑2 ngày trong tuần' },
          { score: 2, text: 'Một vài ngày trong tuần (2‑3 ngày)' },
          { score: 3, text: 'Hơn nửa số ngày trong tuần (4‑5 ngày)' },
          { score: 4, text: 'Hầu như mỗi ngày (6‑7 ngày)' },
          { score: 5, text: 'Liên tục, nguy cơ cao' },
        ],
      },
      {
        type: 'impairment',
        label: 'Ảnh hưởng đến giao tiếp/quan hệ gia đình',
        options: [
          { score: 0, text: 'Không ảnh hưởng đến chức năng' },
          { score: 1, text: 'Ảnh hưởng tối thiểu, hầu như không nhận thấy' },
          { score: 2, text: 'Ảnh hưởng nhẹ đến học tập hoặc quan hệ xã hội' },
          { score: 3, text: 'Ảnh hưởng trung bình đến nhiều lĩnh vực' },
          { score: 4, text: 'Ảnh hưởng nghiêm trọng đến hầu hết lĩnh vực' },
          { score: 5, text: 'Không thể thực hiện chức năng cơ bản' },
        ],
      },
      {
        type: 'duration',
        label: 'Thời gian kéo dài',
        options: [
          { score: 0, text: 'Không có' },
          { score: 1, text: 'Dưới 1 tuần' },
          { score: 2, text: '1‑2 tuần' },
          { score: 3, text: '2‑4 tuần' },
          { score: 4, text: '1‑3 tháng' },
          { score: 5, text: 'Hơn 3 tháng hoặc mạn tính' },
        ],
      },
    ],
  },
  {
    id: 'bullying_victimization',
    label: 'Bị bắt nạn/cô lập',
    categoryCode: 'environment',
    description: 'Một yếu tố nguy cơ lớn cho trầm cảm và tự tử',
    evidenceLevel: 'Strong',
    reference:
      'Kowalski, R.M. et al. (2014). Psychological Bulletin, 140(4), 1073‑1137.',
    questions: [
      {
        type: 'frequency',
        label: 'Tần suất bị bắt nạt/cô lập',
        options: [
          { score: 0, text: 'Không bao giờ hoặc hiếm khi' },
          { score: 1, text: 'Ít hơn 1‑2 ngày trong tuần' },
          { score: 2, text: 'Một vài ngày trong tuần (2‑3 ngày)' },
          { score: 3, text: 'Hơn nửa số ngày trong tuần (4‑5 ngày)' },
          { score: 4, text: 'Hầu như mỗi ngày (6‑7 ngày)' },
          { score: 5, text: 'Liên tục, nguy cơ cao' },
        ],
      },
      {
        type: 'impairment',
        label: 'Ảnh hưởng đến cảm xúc/xã hội',
        options: [
          { score: 0, text: 'Không ảnh hưởng đến chức năng' },
          { score: 1, text: 'Ảnh hưởng tối thiểu, hầu như không nhận thấy' },
          { score: 2, text: 'Ảnh hưởng nhẹ đến học tập hoặc quan hệ xã hội' },
          { score: 3, text: 'Ảnh hưởng trung bình đến nhiều lĩnh vực' },
          { score: 4, text: 'Ảnh hưởng nghiêm trọng đến hầu hết lĩnh vực' },
          { score: 5, text: 'Không thể thực hiện chức năng cơ bản' },
        ],
      },
      {
        type: 'duration',
        label: 'Thời gian kéo dài',
        options: [
          { score: 0, text: 'Không có' },
          { score: 1, text: 'Dưới 1 tuần' },
          { score: 2, text: '1‑2 tuần' },
          { score: 3, text: '2‑4 tuần' },
          { score: 4, text: '1‑3 tháng' },
          { score: 5, text: 'Hơn 3 tháng hoặc mạn tính' },
        ],
      },
    ],
  },
  {
    id: 'academic_pressure',
    label: 'Áp lực học tập',
    categoryCode: 'environment',
    description: 'Áp lực học tập cao trong văn hóa Á Đông',
    evidenceLevel: 'Strong',
    reference:
      'Liu, Y. & Lu, Z. (2012). Educational Psychology, 32(3), 365‑377.',
    questions: [
      {
        type: 'frequency',
        label: 'Tần suất cảm thấy áp lực học tập',
        options: [
          { score: 0, text: 'Không bao giờ hoặc hiếm khi' },
          { score: 1, text: 'Ít hơn 1‑2 ngày trong tuần' },
          { score: 2, text: 'Một vài ngày trong tuần (2‑3 ngày)' },
          { score: 3, text: 'Hơn nửa số ngày trong tuần (4‑5 ngày)' },
          { score: 4, text: 'Hầu như mỗi ngày (6‑7 ngày)' },
          { score: 5, text: 'Liên tục, nguy cơ cao' },
        ],
      },
      {
        type: 'impairment',
        label: 'Ảnh hưởng đến hiệu suất học tập',
        options: [
          { score: 0, text: 'Không ảnh hưởng đến chức năng' },
          { score: 1, text: 'Ảnh hưởng tối thiểu, hầu như không nhận thấy' },
          { score: 2, text: 'Ảnh hưởng nhẹ đến học tập hoặc quan hệ xã hội' },
          { score: 3, text: 'Ảnh hưởng trung bình đến nhiều lĩnh vực' },
          { score: 4, text: 'Ảnh hưởng nghiêm trọng đến hầu hết lĩnh vực' },
          { score: 5, text: 'Không thể thực hiện chức năng cơ bản' },
        ],
      },
      {
        type: 'duration',
        label: 'Thời gian kéo dài',
        options: [
          { score: 0, text: 'Không có' },
          { score: 1, text: 'Dưới 1 tuần' },
          { score: 2, text: '1‑2 tuần' },
          { score: 3, text: '2‑4 tuần' },
          { score: 4, text: '1‑3 tháng' },
          { score: 5, text: 'Hơn 3 tháng hoặc mạn tính' },
        ],
      },
    ],
  },
  {
    id: 'lack_of_support',
    label: 'Thiếu hỗ trợ từ trường/GV',
    categoryCode: 'environment',
    description: 'Gắn liền với cảm giác bị bỏ rơi trong môi trường học',
    evidenceLevel: 'Moderate',
    reference:
      'Cohen, J. et al. (2009). School Climate Research Summary, 1, 1‑6.',
    questions: [
      {
        type: 'frequency',
        label: 'Tần suất cảm thấy thiếu hỗ trợ từ trường/GV',
        options: [
          { score: 0, text: 'Không bao giờ hoặc hiếm khi' },
          { score: 1, text: 'Ít hơn 1‑2 ngày trong tuần' },
          { score: 2, text: 'Một vài ngày trong tuần (2‑3 ngày)' },
          { score: 3, text: 'Hơn nửa số ngày trong tuần (4‑5 ngày)' },
          { score: 4, text: 'Hầu như mỗi ngày (6‑7 ngày)' },
          { score: 5, text: 'Liên tục, nguy cơ cao' },
        ],
      },
      {
        type: 'impairment',
        label: 'Ảnh hưởng đến cảm xúc/xã hội',
        options: [
          { score: 0, text: 'Không ảnh hưởng đến chức năng' },
          { score: 1, text: 'Ảnh hưởng tối thiểu, hầu như không nhận thấy' },
          { score: 2, text: 'Ảnh hưởng nhẹ đến học tập hoặc quan hệ xã hội' },
          { score: 3, text: 'Ảnh hưởng trung bình đến nhiều lĩnh vực' },
          { score: 4, text: 'Ảnh hưởng nghiêm trọng đến hầu hết lĩnh vực' },
          { score: 5, text: 'Không thể thực hiện chức năng cơ bản' },
        ],
      },
      {
        type: 'duration',
        label: 'Thời gian kéo dài',
        options: [
          { score: 0, text: 'Không có' },
          { score: 1, text: 'Dưới 1 tuần' },
          { score: 2, text: '1‑2 tuần' },
          { score: 3, text: '2‑4 tuần' },
          { score: 4, text: '1‑3 tháng' },
          { score: 5, text: 'Hơn 3 tháng hoặc mạn tính' },
        ],
      },
    ],
  },
  {
    id: 'unstable_home',
    label: 'Môi trường sống không ổn định',
    categoryCode: 'environment',
    description: 'Ảnh hưởng nghiêm trọng đến cảm xúc, hành vi và học tập',
    evidenceLevel: 'Strong',
    reference: 'Evans, G.W. (2006). Annual Review of Psychology, 57, 423‑451.',
    questions: [
      {
        type: 'frequency',
        label: 'Tần suất môi trường sống không ổn định',
        options: [
          { score: 0, text: 'Không bao giờ hoặc hiếm khi' },
          { score: 1, text: 'Ít hơn 1‑2 ngày trong tuần' },
          { score: 2, text: 'Một vài ngày trong tuần (2‑3 ngày)' },
          { score: 3, text: 'Hơn nửa số ngày trong tuần (4‑5 ngày)' },
          { score: 4, text: 'Hầu như mỗi ngày (6‑7 ngày)' },
          { score: 5, text: 'Liên tục, nguy cơ cao' },
        ],
      },
      {
        type: 'impairment',
        label: 'Ảnh hưởng đến hành vi/học tập/tâm lý',
        options: [
          { score: 0, text: 'Không ảnh hưởng đến chức năng' },
          { score: 1, text: 'Ảnh hưởng tối thiểu, hầu như không nhận thấy' },
          { score: 2, text: 'Ảnh hưởng nhẹ đến học tập hoặc quan hệ xã hội' },
          { score: 3, text: 'Ảnh hưởng trung bình đến nhiều lĩnh vực' },
          { score: 4, text: 'Ảnh hưởng nghiêm trọng đến hầu hết lĩnh vực' },
          { score: 5, text: 'Không thể thực hiện chức năng cơ bản' },
        ],
      },
      {
        type: 'duration',
        label: 'Thời gian kéo dài',
        options: [
          { score: 0, text: 'Không có' },
          { score: 1, text: 'Dưới 1 tuần' },
          { score: 2, text: '1‑2 tuần' },
          { score: 3, text: '2‑4 tuần' },
          { score: 4, text: '1‑3 tháng' },
          { score: 5, text: 'Hơn 3 tháng hoặc mạn tính' },
        ],
      },
    ],
  },
]

export const reportScore = {
  severity: {
    label: 'reportScore.severity.label',
    options: [
      { score: 0, text: 'reportScore.severity.options.0' },
      { score: 1, text: 'reportScore.severity.options.1' },
      { score: 2, text: 'reportScore.severity.options.2' },
      { score: 3, text: 'reportScore.severity.options.3' },
      { score: 4, text: 'reportScore.severity.options.4' },
      { score: 5, text: 'reportScore.severity.options.5' },
    ],
  },
  frequency: {
    label: 'reportScore.frequency.label',
    options: [
      { score: 0, text: 'reportScore.frequency.options.0' },
      { score: 1, text: 'reportScore.frequency.options.1' },
      { score: 2, text: 'reportScore.frequency.options.2' },
      { score: 3, text: 'reportScore.frequency.options.3' },
      { score: 4, text: 'reportScore.frequency.options.4' },
      { score: 5, text: 'reportScore.frequency.options.5' },
    ],
  },
  impairment: {
    label: 'reportScore.impairment.label',
    options: [
      {
        score: 0,
        text: 'reportScore.impairment.options.0',
      },
      { score: 1, text: 'reportScore.impairment.options.1' },
      { score: 2, text: 'reportScore.impairment.options.2' },
      { score: 3, text: 'reportScore.impairment.options.3' },
      { score: 4, text: 'reportScore.impairment.options.4' },
      {
        score: 5,
        text: 'reportScore.impairment.options.5',
      },
    ],
  },
  chronicity: {
    label: 'reportScore.chronicity.label',
    options: [
      { score: 0, text: 'reportScore.chronicity.options.0' },
      { score: 1, text: 'reportScore.chronicity.options.1' },
      { score: 2, text: 'reportScore.chronicity.options.2' },
      { score: 3, text: 'reportScore.chronicity.options.3' },
      { score: 4, text: 'reportScore.chronicity.options.4' },
      { score: 5, text: 'reportScore.chronicity.options.5' },
    ],
  },
}
