export const surveyData = [
  {
    surveyId: 1,
    name: "Khảo sát tâm lý học đường",
    description: "Khảo sát đánh giá tâm lý học sinh",
    isRequired: true,
    isRecurring: false,
    recurringCycle: "MONTHLY",
    startDate: "2024-01-01",
    endDate: "2024-12-31",
    createdAt: "2025-06-27T07:38:23",
    updatedAt: null,
    status: "ARCHIVED",
    recordStatus: "COMPLETED",
    questions: [
      {
        questionId: 1,
        createdAt: "2025-06-27T07:38:23",
        updatedAt: null,
        description: "Đánh giá mức độ áp lực từ việc học.",
        moduleType: "SURVEY",
        questionType: "MULTIPLE_CHOICE",
        category: {
          id: 1,
          name: "Tâm lý học đường",
          code: "PSY",
        },
        text: "Bạn có thường xuyên cảm thấy bị quá tải với khối lượng bài tập và kỳ vọng học tập không?",
        answers: [
          {
            id: 1,
            text: "Có",
            score: 1,
          },
          {
            id: 2,
            text: "Không",
            score: 0,
          },
        ],
        active: true,
        required: true,
      },
    ],
  },
  {
    surveyId: 2,
    name: "Test",
    description: "string",
    isRequired: true,
    isRecurring: true,
    recurringCycle: "DAILY",
    startDate: "2025-06-27",
    endDate: "2025-06-29",
    createdAt: "2025-06-27T10:25:27.051248",
    updatedAt: "2025-06-27T10:25:27.051275",
    status: "PUBLISHED",
    recordStatus: "NOT_STARTED",
    questions: [
      {
        questionId: 2,
        createdAt: "2025-06-27T10:25:27.086534",
        updatedAt: "2025-06-27T10:25:27.086549",
        description: "string",
        moduleType: "SURVEY",
        questionType: "SINGLE_CHOICE",
        category: {
          id: 1,
          name: "Tâm lý học đường",
          code: "PSY",
        },
        text: "string",
        answers: [
          {
            id: 3,
            text: "string",
            score: 0,
          },
          {
            id: 4,
            text: "string",
            score: 1,
          },
        ],
        active: true,
        required: true,
      },
      {
        questionId: 3,
        name: "Test 1",
        description: "string",
        isRequired: true,
        isRecurring: true,
        recurringCycle: "DAILY",
        createdAt: "2025-06-27T10:25:27.1014",
        updatedAt: "2025-06-27T10:25:27.101415",
        description: "string",
        moduleType: "SURVEY",
        questionType: "SINGLE_CHOICE",
        category: {
          id: 1,
          name: "Tâm lý học đường",
          code: "PSY",
        },
        text: "string",
        answers: [
          {
            id: 5,
            text: "string",
            score: 0,
          },
          {
            id: 6,
            text: "string",
            score: 1,
          },
        ],
        active: true,
        required: true,
      },
    ],
  },
  {
    surveyId: 4,
    name: "Test 2",
    description: "string",
    isRequired: true,
    isRecurring: true,
    recurringCycle: "DAILY",
    startDate: "2025-06-28",
    endDate: "2025-07-05",
    createdAt: "2025-06-27T10:28:03.11668",
    updatedAt: "2025-06-27T10:28:03.116695",
    status: "PUBLISHED",
    recordStatus: "NOT_STARTED",
    questions: [
      {
        questionId: 4,
        createdAt: "2025-06-27T10:28:03.124911",
        updatedAt: "2025-06-27T10:28:03.124952",
        description: "string",
        moduleType: "SURVEY",
        questionType: "SINGLE_CHOICE",
        category: {
          id: 1,
          name: "Tâm lý học đường",
          code: "PSY",
        },
        text: "string",
        answers: [
          {
            id: 7,
            text: "string",
            score: 0,
          },
          {
            id: 8,
            text: "string",
            score: 1,
          },
        ],
        active: true,
        required: true,
      },
      {
        questionId: 5,
        createdAt: "2025-06-27T10:28:03.133327",
        updatedAt: "2025-06-27T10:28:03.133342",
        description: "string",
        moduleType: "SURVEY",
        questionType: "SINGLE_CHOICE",
        category: {
          id: 1,
          name: "Tâm lý học đường",
          code: "PSY",
        },
        text: "string",
        answers: [
          {
            id: 9,
            text: "string",
            score: 0,
          },
          {
            id: 10,
            text: "string",
            score: 1,
          },
        ],
        active: true,
        required: true,
      },
    ],
  },
  {
    surveyId: 5,
    name: "Khảo sát sức khỏe tâm thần",
    description: "Đánh giá tình trạng sức khỏe tâm thần của học sinh",
    isRequired: false,
    isRecurring: true,
    recurringCycle: "WEEKLY",
    startDate: "2025-01-01",
    endDate: "2025-12-31",
    createdAt: "2025-06-27T10:30:00.000000",
    updatedAt: "2025-06-27T10:30:00.000000",
    status: "PUBLISHED",
    recordStatus: "COMPLETED",
    questions: [
      {
        questionId: 6,
        createdAt: "2025-06-27T10:30:00.000000",
        updatedAt: "2025-06-27T10:30:00.000000",
        description: "Đánh giá mức độ stress",
        moduleType: "SURVEY",
        questionType: "SINGLE_CHOICE",
        category: {
          id: 2,
          name: "Sức khỏe tâm thần",
          code: "MENTAL",
        },
        text: "Bạn có thường xuyên cảm thấy căng thẳng không?",
        answers: [
          {
            id: 11,
            text: "Rất thường xuyên",
            score: 3,
          },
          {
            id: 12,
            text: "Thỉnh thoảng",
            score: 2,
          },
          {
            id: 13,
            text: "Hiếm khi",
            score: 1,
          },
          {
            id: 14,
            text: "Không bao giờ",
            score: 0,
          },
        ],
        active: true,
        required: true,
      },
    ],
  },
];
